version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-west-2"
    HUGO_VERSION: "0.70.0"
    HUGO_SHA256: "494fdb1c95675f9477d0279343a067a17b340a7d3c104f285bd745790e3bfc72"
    NODE_ENV: "development"
    HUGO_ENV: "production"

phases:
  install:
    commands:
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - echo "${HUGO_SHA256}  /tmp/hugo.tar.gz" | sha256sum -c -
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
  pre_build:
    commands:
      - git submodule update --init --recursive
      - npm ci
      - rm -rf /tmp/hugo_cache/
      - rm -rf ./public
  build:
    commands:
      - hugo -b https://danielmuller.me/ --gc --minify
  post_build:
    commands:
      - bash bin/alias/build
      - hugo deploy
      - bash bin/alias/push
cache:
  paths:
    - 'node_modules/**/*'
    - 'resources/**/*'
