languageCode = "en"
title = "Daniel Muller"
baseURL = ""
theme = "origin"
timeout = 300000
PygmentsCodeFences = true
pygmentsuseclasses = true
enableRobotsTXT = true

[params]
    description = "A Swiss Geek previously in Singapore, now in Portugal"
    locale = "en_US"
    logo = "/logos/favicon-120x120.png"
    ampElements = ["amp-analytics", "amp-twitter"]
    themeColor = "#ffffff"
    googleanalytics = "UA-1341906-8"
    defaultSchema = "article"
[permalinks]
    post = '/:year/:month/:slug/'
[outputs]
    home = [ "HTML", "RSS"]
    page = [ "HTML"]
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[author]
    name = "Daniel Muller"
    bio = "<p>After several years breathing PHP, Perl, Python, Bash and bare-metal as multipurpose SysAdmin in a swiss geospatial company Geomatic, I exchanged snow, cows, mountains and maps for sun, chicken rice, flip-flops and movies.</p><p>I worked for 9 years in a Singaporean Start-up <a href=\"https://spuul.com/\" target=\"_blank\">Spuul</a>, breathing Ruby, Bash and AWS first as SysAdmin and later as Head of Cloud Infrastructure with the same multipurpose Swiss-Army knife style.</p><p>I moved now to Portugal, looking for the next gig.</p>"
    shortbio = ""
    location = "Portugal"
    website = "https://daniel.ctrlaltdel.ch"
    twitter = "DanielMullerCH"
    github = "DanielMuller"
    linkedin = "danielmullerch"
    flipboard = "danielmuller"
    devto = "danielmuller"
    reddit = "DanielMullerCH"

[params.share]
    twitter = true
    gplus = true
    pinterest = true
    facebook = true

[params.favicon]
    manifest = "manifest.json"
    basename = "/logos/favicon"
    ms_tilecolor = "#FFFFFF"
    icon = [16, 32, 96, 192]
    apple_touch = [57, 60, 72, 76, 114, 120, 144, 152, 180]
    ms = [144]
    ms_config = "browserconfig.xml"

[[menu.links]]
    pre = "My Stuff"
    name = 'Follow me'
    weight = 210
    url = 'https://daniel.ctrlaltdel.ch/'
[[menu.links]]
    name = 'My photo gallery'
    weight = 220
    url = 'https://daniel.mesphotos.ch/'
[[menu.links]]
    name = 'My personal blog'
    weight = 230
    url = 'https://farfromhome.asia/'

[imaging]
  resampleFilter = "CatmullRom"
  quality = 95
  
[imaging.exif]
  includeFields = ""

[markup.goldmark.renderer]
  unsafe= true

[deployment]
[[deployment.targets]]
name = "production"
URL = "s3://danielmuller.me?region=us-west-2"
cloudFrontDistributionID = "E15XC7I4SGL3JX"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
