---
upload_path: "/src/images/:year:/:month:/:day:"
frontmatter_file_url_template: "/images/:year:/:month:/:day:"
body_file_url_template: "/images/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
  post:
    default_front_matter_template: post
version: 0.31.1
